language: node_js
node_js:
  - "node"
  - "6"
matrix:
  include:
  - node_js: "iojs"
    install: npm install
after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
cache:
  yarn: true
